version: '3'  
services:  
  db:  
    image: postgres:latest  
    restart: always  
    ports:  
      - 5432:5432  
    environment:  
      POSTGRES_DB: event-management_db  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password  
    volumes:  
      - db:/var/lib/postgresql/data  
  flyway:  
    image: flyway/flyway  
    command: -url=jdbc:postgresql://db/event-management_db -schemas=public -user=postgres  
      -password=password -connectRetries=5 migrate  
    volumes:  
      - ./database:/flyway/sql  
    depends_on:  
      - db  
  api:
    profiles: ["be"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/event-management_db?schema=public"
    # healthcheck:
    #     # test: curl --fail http://localhost:3001/swaggerr.json || exit 1
    #     test: ["CMD", "curl", "-f", "http://backend:3015/readiness"]
    #     interval: 60s
    #     retries: 5
    #     start_period: 20s
    #     timeout: 10s
  ui:
    profiles: ["fe"]
    build:
      context: ./ui
      dockerfile: Dockerfile.local
    volumes:
      - ./ui:/app
    ports:
      - "5173:5173"
    # healthcheck:
    #     test: curl --fail http://localhost:5173/swagger.json || exit 1
    #     interval: 60s
    #     retries: 5
    #     start_period: 20s
    #     timeout: 10s
volumes:  
  db: